# Generated by Django 4.2 on 2024-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interiors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                ("input_image", models.ImageField(upload_to="uploads/")),
                ("generated_image", models.ImageField(upload_to="generated/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
